style_matplotlib: seaborn

AE:
  model_path: ./results/10001/checkpoint

Re_Training:
  active: False
  model_path: None

number_of_global_variables: 2
steps_per_episode: 40
delta_value: 1
total_timesteps: 1000000

# Type action space
# 1. BoxSpaceAction
# 2. DiscreteAction
action_space: BoxSpaceAction

# type agent :
# 1.
# 2.
# 3.
type_agent: PPO

#type reward
# i tipi di reward sono defini attraverso le funzioni che troviamo nel file rewaed_functions
# 1. step_reward
# 2. best_value_reward
# 3. min_value_reward
# 4. max_value_reward
# 5. final_start_value_reward
# 6. final_sumGV_reward
type_rewards: final_sumGV_reward

agent_config:
  #type policy network
  # 1. MlpPolicy:
  # 2. MlpLstmPolicy
  # 3. MlpLnLstmPolicy
  policy_network: MlpPolicy


fit_params:
  order: 9
  sub_geom: 1
  alpha: 0.02162995824037003
  th_x: 0.01

